export const series = [
  {
    id: 1,
    name: "Czarnobyl",
    startYear: 2019,
    endYear: 2019,
    type: ["Dramat"],
    seasons: 1,
  },
  {
    id: 2,
    name: "Przyjaciele",
    startYear: 1994,
    endYear: 2004,
    type: ["Komedia"],
    seasons: 10,
  },
  {
    id: 3,
    name: "Dr House",
    startYear: 2004,
    endYear: 2012,
    type: ["Dramat", "Komedia"],
    seasons: 8,
  },
  {
    id: 4,
    name: "Jak poznałem waszą matkę",
    startYear: 2005,
    endYear: 2014,
    type: ["Komedia"],
    seasons: 9,
  },
  {
    id: 5,
    name: "Lucyfer",
    startYear: 2016,
    endYear: 2021,
    type: ["Fantasy", "Kryminał"],
    seasons: 6,
  },
  {
    id: 6,
    name: "Dobre miejsce",
    startYear: 2016,
    endYear: 2020,
    type: ["Komedia"],
    seasons: 4,
  },
  {
    id: 7,
    name: "Emily w Paryżu",
    startYear: 2020,
    endYear: null,
    type: ["Dramat", "Komedia", "Romans"],
    seasons: 2,
  },
  {
    id: 8,
    name: "Szpital New Amsterdam",
    startYear: 2018,
    endYear: null,
    type: ["Dramat"],
    seasons: 4,
  },
  {
    id: 9,
    name: "Kompania braci",
    startYear: 2001,
    endYear: 2001,
    type: ["Dramat", "Wojenny"],
    seasons: 1,
  },
  {
    id: 10,
    name: "Outlander",
    startYear: 2014,
    endYear: null,
    type: ["Dramat", "Kostiumowy", "Romans", "Sci-Fi"],
    seasons: 6,
  },
  {
    id: 11,
    name: "House of Cards",
    startYear: 2013,
    endYear: 2018,
    type: ["Dramat", "Polityczny"],
    seasons: 6,
  },
  {
    id: 12,
    name: "Brooklyn 9-9",
    startYear: 2013,
    endYear: 2022,
    type: ["Komedia kryminalna"],
    seasons: 8,
  },
  {
    id: 13,
    name: "Biuro",
    startYear: 2005,
    endYear: 2013,
    type: ["Komedia"],
    seasons: 9,
  },
  {
    id: 14,
    name: "Rick i Morty",
    startYear: 2013,
    endYear: null,
    type: ["Komedia", "Przygodowy", "Sci-Fi", "Animacja dla dorosłych"],
    seasons: 9,
  },
  {
    id: 15,
    name: "Squid Game",
    startYear: 2021,
    endYear: null,
    type: ["Dramat", "Thriller"],
    seasons: 9,
  },
  {
    id: 16,
    name: "Dom z papieru",
    startYear: 2017,
    endYear: 2021,
    type: ["Thriller", "Akcja"],
    seasons: 9,
  },
  {
    id: 17,
    name: "Gambit królowej",
    startYear: 2020,
    endYear: 2020,
    type: ["Dramat"],
    seasons: 1,
  },
  {
    id: 18,
    name: "Ania, nie Anna",
    startYear: 2017,
    endYear: 2019,
    type: ["Dramat"],
    seasons: 3,
  },
  {
    id: 19,
    name: "W garniturach",
    startYear: 2011,
    endYear: 2019,
    type: ["Dramat"],
    seasons: 9,
  },
  {
    id: 20,
    name: "Pacyfik",
    startYear: 2010,
    endYear: 2010,
    type: ["Dramat", "Wojenny"],
    seasons: 1,
  },
];
